In [2]:
import tensorflow as tf

# 定義一個隨機數（純量）
random_float = tf.random.uniform(shape=(10,1)) *10
X = random_float
w = tf.constant([6.7])
b = tf.constant([-3.3])
Y =  w * X + b
# Y = tf.matmul(X, w) # 計算矩陣A和B的乘積
# Y = tf.add(Y, b)    # 計算矩陣A和B的和

# 定義一個有2個元素的零向量
zero_vector = tf.zeros(shape=(2))

# 定義兩個2×2的常量矩陣
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])


2022-09-28 16:27:07.788960: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-28 16:27:08.354212: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/foxy/opt/yaml_cpp_vendor/lib:/opt/ros/foxy/opt/rviz_ogre_vendor/lib:/opt/ros/foxy/lib/x86_64-linux-gnu:/opt/ros/foxy/lib
2022-09-28 16:27:08.354264: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 

In [3]:
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
wg = tf.Variable(initial_value=0.)
bg = tf.Variable(initial_value=0.)
variables = [wg, bg]
print(X)

num_epoch = 1000
for e in range(num_epoch):
    # 使用tf.GradientTape()記錄損失函數的梯度資訊
    with tf.GradientTape() as tape:
        y_pred = wg * X + bg
        loss = tf.reduce_sum(tf.square(y_pred - Y)) / 10
    # TensorFlow自動計算損失函數關於自變數（模型參數）的梯度
    grads = tape.gradient(loss, variables)
    # TensorFlow自動根據梯度更新參數
    optimizer.apply_gradients(grads_and_vars=zip(grads, variables))

print(grads)
print(wg, bg)

tf.Tensor(
[[4.2864504 ]
 [0.0506258 ]
 [6.646638  ]
 [2.063229  ]
 [4.3012834 ]
 [0.11221647]
 [2.6017559 ]
 [8.352058  ]
 [1.313479  ]
 [2.5801504 ]], shape=(10, 1), dtype=float32)
[<tf.Tensor: shape=(), dtype=float32, numpy=-0.0003633038>, <tf.Tensor: shape=(), dtype=float32, numpy=0.0018620015>]
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=6.6995196> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-3.2975235>


In [4]:
# X = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# Y = tf.constant([[10.0], [20.0]])


class Linear(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.dense = tf.keras.layers.Dense(
            units=1,
            activation=None,
            kernel_initializer=tf.zeros_initializer(),
            bias_initializer=tf.zeros_initializer()
        )

    def call(self, input):
        output = self.dense(input)
        return output


# 以下程式碼結構與前一節類似
model = Linear()
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
for i in range(1000):
    with tf.GradientTape() as tape:
        y_pred = model(X)      # 呼叫模型 y_pred = model(X) 而不是顯式寫出 y_pred = a * X + b
        loss = tf.reduce_mean(tf.square(y_pred - Y))
        # loss = tf.reduce_sum(tf.square(y_pred - Y)) / 10
    grads = tape.gradient(loss, model.variables)    # 使用 model.variables 這一屬性直接獲得模型中的所有變數
    optimizer.apply_gradients(grads_and_vars=zip(grads, model.variables))
print(model.variables)

tf.Tensor(632.2003, shape=(), dtype=float32)
tf.Tensor(268.952, shape=(), dtype=float32)
tf.Tensor(116.830734, shape=(), dtype=float32)
tf.Tensor(53.08904, shape=(), dtype=float32)
tf.Tensor(26.34431, shape=(), dtype=float32)
tf.Tensor(15.087604, shape=(), dtype=float32)
tf.Tensor(10.315127, shape=(), dtype=float32)
tf.Tensor(8.257891, shape=(), dtype=float32)
tf.Tensor(7.33814, shape=(), dtype=float32)
tf.Tensor(6.895421, shape=(), dtype=float32)
tf.Tensor(6.653244, shape=(), dtype=float32)
tf.Tensor(6.495861, shape=(), dtype=float32)
tf.Tensor(6.3748074, shape=(), dtype=float32)
tf.Tensor(6.26978, shape=(), dtype=float32)
tf.Tensor(6.172273, shape=(), dtype=float32)
tf.Tensor(6.078705, shape=(), dtype=float32)
tf.Tensor(5.9875712, shape=(), dtype=float32)
tf.Tensor(5.8982334, shape=(), dtype=float32)
tf.Tensor(5.810405, shape=(), dtype=float32)
tf.Tensor(5.7239594, shape=(), dtype=float32)
tf.Tensor(5.6388283, shape=(), dtype=float32)
tf.Tensor(5.554979, shape=(), dtype=float32)
tf.T